[env:rpipico]
platform = raspberrypi
board = rpipico
framework = arduino

upload_protocol = jlink
debug_tool = jlink

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D__FREERTOS=1

monitor_speed = 115200

;monitor_port = COM12


lib_deps =
    teemuatlut/TMCStepper @ ^0.7.3
    waspinator/AccelStepper @ ^1.64
    https://github.com/gin66/FastAccelStepper